### ISSUE TITLE
Error in the derivation of the mean of the normal variable?

### ISSUE THREAD

**Issue by heliosdrm** [abhranildas/gx2#1]
In the derivation of the gx2 distribution from a quadratic form, the mean of the normal variable is calculated as:
https://github.com/abhranildas/gx2/blob/06edc5cbdf97a76c9139428af7ffd98e778f3238/gx2_params_norm_quad.m#L60

This agrees with the formula given in the paper (https://arxiv.org/abs/2012.14331):
$m = q(\mathbf{\mu}) -  \mathbf{w}\cdot\mathbf{\lambda}$

But it seems to me that there is an error, and it should be:
$m = q(\mathbf{\mu}) -  \mathbf{k}\cdot\mathbf{\lambda}$
(i.e. the noncentrality parameters should be weighed by the degrees of freedom of the Chi-squared distributions, $\mathbf{k}$).

That mean is derived from a previous formula in the paper, where the normal variable is defined as:
$\sum{b_{i^\prime} y_{i^\prime}} + \tilde{q_0} - \sum{\(\frac{b_i}{2D_i}\)^2} $

The mean of that variable is meant to be the the value of that variable when $y_{i^\prime} = 0$, i.e.:
$\tilde{q_0} - \sum{\(\frac{b_i}{2D_i}\)^2} $

Now, $\tilde{q}_0$ is defined as $q(\mathbf{\mu})$, which accounts for the first term; and the elements in the sum of the second term correspond to the definition of $\lambda_j$, for the unique values of the eigenvalues $D_i$.

Therefore, if I have followed that derivation correctly, each value of $\lambda_j$ should be weighed by the *number of eigenvalues* that are equal to $\lambda_j$ (i.e. the degrees of freedom $k_i$), and not the values of the eigenvalues ($w_j$).

**Comment by heliosdrm** [comment]
I realised that the definition of the mean and the code are right, but the formula where it is derived in the paper from had a mistake. It is printed as:

$\hat{q}(\mathbf{y}) = ... = \sum{D_{i}\(y_{i}+\frac{b_i}{2D_i}\)^2} + \sum{b_{i^\prime}y_{i^\prime}} + \tilde{q}_0 - \sum{\(\frac{b_i}{2D_i}\)^2}$

But it should be:
$\hat{q}(\mathbf{y}) = ... = \sum{D_{i}\(y_{i}+\frac{b_i}{2D_i}\)^2} + \sum{b_{i^\prime}y_{i^\prime}} + \tilde{q}_0 - \sum{D_i\(\frac{b_i}{2D_i}\)^2}$

i.e. the last sum should include the factor $D_i$, which is the source of the vector $w$ in the subsequent definition of the mean.

**Comment by abhranildas** [comment]
Hello Helios, thanks for your observation and the effort you put in to describe the issue so clearly. I just looked through it and you are exactly right. Thankfully, the final math result and code are correct, but there was that mistake in that intermediate step. Without your observation and comment, we would never have noticed the error. I have corrected it in my paper and will update the arxiv version at some point soon, and also include you in the acknowledgments. I'll also get in touch with my advisor about sending a correction to Journal of Vision. Thanks a lot again!

**Comment by heliosdrm** [comment]
Thanks for your appreciation, and also for pointing out the version published in Journal of Vision, very useful to refer to.

**Comment by abhranildas** [comment]
Hello Helios, Journal of Vision never responded to my request to correct
the typo you found. But I updated it on our arxiv version
<https://arxiv.org/abs/2012.14331> and added you in the acknowledgements.
Thank you again.

Abhranil Das
